<?php

/**
 * @file
 * Module file for symfony_mailer_log.
 */

/**
 * Implements hook_cron().
 */
function symfony_mailer_log_cron() {
  try {
    /** @var \Drupal\symfony_mailer_log\SymfonyMailerLogStorageInterface $storage */
    $storage = Drupal::entityTypeManager()->getStorage('symfony_mailer_log');
    /** @var \Drupal\symfony_mailer_log\Config\SymfonyMailerLogSettingsConfig $settings_config */
    $settings_config = Drupal::service('symfony_mailer_log.settings_config');
    $maximum_age = $settings_config->getLogExpiryMaxAge();
    $batch_size = $settings_config->getLogExpiryBatchSize();
    if ($maximum_age) {
      $storage->deleteExpiredBatched($maximum_age, $batch_size);
    }
  }
  catch (Exception $ex) {
    \Drupal::logger('symfony_mailer_log')->error($ex->getMessage());
  }

}
