<?php
use Drupal\profile\Entity\Profile;
use Symfony\Component\HttpFoundation\RequestStack;
use Drupal\Core\Entity\EntityStorageInterface;
/**
 * @file
 * Primary module hooks for NBW Data App module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function nbw_data_app_preprocess_webform_confirmation(&$vars) {

  $formsToProcess = [
    'bike-church-patron-waiver',
    'nbw_youth_application_waiver',
  ];

  if ($vars['webform']->id() == 'bike_church_patron_waiver') {

    $webform_submission = $vars['webform_submission'];

    $address = $webform_submission->getElementData('name_and_address_');

    $name = $address['given_name'] . ' ' . $address['family_name'];

    $markup = t('Thank you, the form was submitted for ') . $name;

    $vars['message']['#markup'] = $markup;
  }
  elseif ($vars['webform']->id() == 'nbw_youth_application_waiver'){
    $webform_submission = $vars['webform_submission'];
    $address = $webform_submission->getElementData('youth_address');
    $name = $address['given_name'] . ' ' . $address['family_name'];
    $markup = t('Thank you, the Waiver was recorded for ') . $name;
    $vars['message']['#markup'] = $markup;
  }
}

/**
 * Implements hook_form_alter().
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 * @return void
 */
function nbw_data_app_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  //dpm('from my module: ' . $form_id);
  //\Drupal::messenger()->addMessage(t("form id is - " . $form_id));
  $form['#attached']['library'][] = 'nbw_data_app/nbw_style';
    if ($form_id == 'user_form') {
      //dpm($form['actions']);
/*      \Drupal::messenger()->addMessage(t("We're about to edit this user!!"));*/

      $user = $form_state->getFormObject()->getEntity();

      $nbw_youth_profile = \Drupal::entityTypeManager()
        ->getStorage('profile')
        ->loadByProperties([
          'uid' => $user->id(),
          'type' => 'nbw_youth_profile',
        ]);
      //dpr($nbw_youth_profile);
      //$form['actions']['submit']['#value'] = t("Save this awesome article!");

    } elseif ($form_id == 'webform_submission_check_in_students_to_mon_wed_sum_add_form') {
      \Drupal::messenger()->addMessage(t("form id is - " . $form_id));
      //dpr($form_state);
    }

  // Check if this is the special form for "Drop In Class Record".
  if (\Drupal::routeMatch()->getRouteName() == 'entity.node.add_form' && $form['#node']->bundle() == 'attendance_record') {
    // Change the form title.
    $form['#title'] = t('Create Drop In Class Record');

    // Find or create today's class session.
    $today = new \DateTime('today');
    $query = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
      ->condition('type', 'class_session')
      ->condition('field_class_date', $today->format('Y-m-d'));

    $nids = $query->execute();
    if (!empty($nids)) {
      $class_session_id = reset($nids);
      $form['field_class_session_record']['#default_value'] = $class_session_id;
    }
  }
}

/**
 * Implements Implements hook_form_FORM_ID_alter() for node_class_registration_form.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 * @return void
 */
function nbw_data_app_form_node_class_registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  if ($form_id == 'node_class_registration_form') {
    //$request = \Drupal::request();
    $destination = \Drupal::request()->query->get('destination');
    $node_id = NULL;

    // Extract the node ID from the destination parameter.
    if (preg_match('/\/node\/(\d+)$/', $destination, $matches)) {
      $node_id = $matches[1];
    }

    if ($node_id && is_numeric($node_id)) {
      //autocomplete select field reference
      $form['field_class_name']['widget']['#default_value'] = $node_id;
      //disable field
      $form['field_class_name']['#disabled'] = TRUE;
      //pass my ID like argument in my field to filter only pages referenced
      //$form['field_liste_ref_dossier']['widget']['target_id']['#selection_settings']['view']['arguments'][] = $nid;
    }

  }
}

/**
 * Implements Implements hook_form_FORM_ID_alter() for node-attendance-record-form.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 * @return void
 */
function nbw_data_app_form_node_attendance_record_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  if ($form_id == 'node_attendance_record_form') {
    //$request = \Drupal::request();
    $destination = \Drupal::request()->query->get('destination');
    $node_id = NULL;

    // Extract the node ID from the destination parameter.
    if (preg_match('/\/node\/(\d+)$/', $destination, $matches)) {
      $node_id = $matches[1];
    }

    if ($node_id && is_numeric($node_id)) {
      //autocomplete select field reference
      $form['field_class_name']['widget']['#default_value'] = $node_id;
      //disable field
      $form['field_class_name']['#disabled'] = TRUE;

//      $form['field_end_time']['widget']['#default_value'] = NULL;
//      $form['field_end_time']['#disabled'] = TRUE;

      //pass my ID like argument in my field to filter only pages referenced
      //$form['field_liste_ref_dossier']['widget']['target_id']['#selection_settings']['view']['arguments'][] = $nid;
    }

    //$now = \Drupal::time()->getRequestTime();
    //$form['field_start_time']['widget']['#default_value'] = $now;
    //$form['field_start_time']= $now;

  }
}

/**
 * Implements Implements hook_form_FORM_ID_alter() for node-graduation-record-form.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 * @return void
 */
function nbw_data_app_form_node_graduation_record_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  if ($form_id == 'node_graduation_record_form') {
    //$request = \Drupal::request();
    $destination = \Drupal::request()->query->get('destination');
    $node_id = NULL;

    // Extract the node ID from the destination parameter.
    if (preg_match('/\/node\/(\d+)$/', $destination, $matches)) {
      $node_id = $matches[1];
    }

    if ($node_id && is_numeric($node_id)) {
      //autocomplete select field reference
      $form['field_class_name']['widget']['#default_value'] = $node_id;
      //disable field
      $form['field_class_name']['#disabled'] = TRUE;

      //      $form['field_end_time']['widget']['#default_value'] = NULL;
      //      $form['field_end_time']['#disabled'] = TRUE;

      //pass my ID like argument in my field to filter only pages referenced
      //$form['field_liste_ref_dossier']['widget']['target_id']['#selection_settings']['view']['arguments'][] = $nid;
    }

    //$now = \Drupal::time()->getRequestTime();
    //$form['field_start_time']['widget']['#default_value'] = $now;
    //$form['field_start_time']= $now;

  }
}


/**
 * Implements hook_entity_id_insert().

 * @param \Drupal\Core\Entity\EntityInterface $entity

 *
 * @return void
 */
//nbw_data_app_entity_insert
function nbw_data_app_webform_submission_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  //dpr($entity);
  \Drupal::messenger()->addMessage(t("webform id is: " . $entity->getWebform()->id()));
  if ($entity->getWebform()->id() == 'record_volunteer_time' ){
    $webfor_data = $entity->getData();
    $hours = $webfor_data['number_of_hours'];
    $volunteer = $webfor_data['volunteer_'];
    $nbw_record_profiles = \Drupal::entityTypeManager()
      ->getStorage('profile')
      ->loadByProperties([
        'uid' => $volunteer,
        'type' => 'nbw_volunteer_profile',
      ]);
    if(!empty($nbw_record_profiles)) {
      foreach ($nbw_record_profiles as $profile) {
        //dpm($profile->get('field_miles_total')->value);
        $hours_total_new = floatval($profile->get('field_hours_total')->value) + $hours;
        $profile->get('field_hours_total')->setValue($hours_total_new);
        $profile->save();
      }
    } else {
      $nbw_volunteer_profile = Profile::create([
        'type' => 'nbw_volunteer_profile',
        'uid' => $volunteer,
        'field_hours_total' => $hours,
      ]);
      $nbw_volunteer_profile->save();
    }

  }

/*  $miles = $entity->get('miles_ridden')->getValue();
  $hours = $entity->get('hours')->getValue();

  $riders = $entity->get('riders')->getValue();

  \Drupal::messenger()->addMessage(t("hours: " . $hours . " miles: " . $miles));*/
  //dpm($miles);
/*  $attendees = $form_state->getValue('field_youth_attended');
  //dpm($attendees);

  foreach($attendees as $youth) {

    // Get NBW profiles by the YouthID
    $nbw_record_profiles = \Drupal::entityTypeManager()
      ->getStorage('profile')
      ->loadByProperties([
        'uid' => $youth,
        'type' => 'nbw_record',
      ]);

    foreach($nbw_record_profiles as $profile) {
      //dpm($profile->get('field_miles_total')->value);
      $miles_total_new = floatval($profile->get('field_miles_total')->value) + $miles;
      $hours_total_new = floatval($profile->get('field_hours_total')->value) + $hours;
      $profile->get('field_miles_total')->setValue($miles_total_new);
      $profile->get('field_hours_total')->setValue($hours_total_new);
      $profile->save();
    }

  }*/
  //$entity->webform_id
}

/**
 * Implements hook_element_info_alter().
 */
function nbw_data_app_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'nbw_data_app/toolbar';
  }
}
/**
 * Implements hook_theme_suggestions_HOOK_alter() to exclude specific templates.
 */
//function nbw_data_app_theme_suggestions_government_banner_alter(array &$suggestions, array $variables, $hook) {
  // Specify the template you want to exclude.
/*  $excluded_template = 'government_banner';

  // Check if the current template should be excluded.
  if ($hook === $excluded_template) {
    // Add a suggestion that points to an empty template.
    $suggestions[] = $excluded_template . '__excluded';
  }*/
/*  if (($key = array_search('government_banner', $suggestions)) !== false) {
    // Remove the existing template suggestion.
    unset($suggestions[$key]);
  }*/
//}
//function nbw_data_app_preprocess_government_banner(array &$variables) {
  // Modify variables or add custom logic here.
  // For example, you can add or alter variables used in the template.
  // Example:
   //$variables['my_custom_variable'] = 'Custom value';
//}



/*function nbw_data_app_views_pre_execute(&$view) {
  dpq($view->build_info['query']);
}*/
//webform_submission
function nbw_data_app_cron() {
  $current_time = new \DateTime();
  $class_end_time = new \DateTime('14:00');

  if ($current_time >= $class_end_time) {
    $query = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
      ->condition('type', 'attendance_record')
      ->condition('field_time_out', NULL, 'IS NULL')
      ->condition('field_class_session_record.entity.field_end_time', '14:00:00');

    $nids = $query->execute();
    if (!empty($nids)) {
      foreach ($nids as $nid) {
        $attendance_record = \Drupal\node\Entity\Node::load($nid);
        $attendance_record->set('field_time_out', $class_end_time->format('H:i:s'));
        $attendance_record->set('field_auto_checked_out', TRUE);
        $attendance_record->save();

        // Log an alert for admin.
        \Drupal::logger('attendance')->notice('Youth auto-checked out for node ID: @nid', ['@nid' => $nid]);
      }
    }
  }
}

